export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';

export const ADD_TO_FAVOURITE = 'ADD_TO_FAVOURITE';
export const DELETE_ITEM_FAVOURITE = 'DELETE_ITEM_FAVOURITE';
